title: My First Blog
author: Shivang-Dhimmar
email: shivang3921dhimmar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shivang Dhimmar First Blog.

# social links
theme : minima
show_excerpts: true # set to false to remove excerpts on the homepage
